apiVersion: apps/v1
kind: Deployment
metadata:
  name: trab
spec:
  selector:
    matchLabels:
      app: trab
  template:
    metadata:
      labels:
        app: trab
    spec:
      containers:
      - name: trab
        image: jaquelinearaujo/trab
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
